# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Singcodes
paginate:       5
baseurl:        ""
url:            "https://singcodes.github.io"

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Kwanghoon Choi
  url:          https://singcodes.github.io
  email:        eyerama@gmail.com

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/chesterhow/tale

# Gems
gems:
  - jekyll-paginate
